### ISSUE TITLE
Buff

### ISSUE THREAD

**Issue by hemisfere** [Ihellmasker/BDO-Planner#10]
- alchemy 
- cook

**Comment by Ihellmasker** [comment]
What do you mean?

**Comment by Shadowtrance** [comment]
This is not helpful at all...
Maybe post a short sentence of what the actual issue is, we aren't mind readers.
This is basically like someone commenting and saying "hey, it doesn't work!"... **WHAT** doesn't work, or in this case, **WHAT** is the issue.
Yes, I'm going to keep repeating myself...

**Comment by hemisfere** [comment]
I want to say, you could add other details such as the effects of alchemy and alchemy ..

**Comment by hemisfere** [comment]
For calculate the easier everything we need..
