### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by hemisfere** [Ihellmasker/BDO-Planner#11]
- all character stats

**Comment by Ihellmasker** [comment]
What's missing other than non combat related stats?

**Comment by Shadowtrance** [comment]
This is not helpful at all...
Maybe post a short sentence of what the actual issue is, we aren't mind readers.
This is basically like someone commenting and saying "hey, it doesn't work!"... **WHAT** doesn't work, or in this case, **WHAT** is the issue.
