### ISSUE TITLE
DP stats on Jubre Talismans

### ISSUE THREAD

**Issue by Lorizean** [Ihellmasker/BDO-Planner#14]
The DP for the enchantments of Jubre Talismans are wrong:

- The green one doesn't have any DP in the tool (should be 1 for PRI to 5 for PENT)
- The blue ones and the ultimate are missing the 1 DP for PRI (they have the correct DP for DUO onwards)

**Comment by Shadowtrance** [comment]
thanks for the report. fixed. :)
