### ISSUE TITLE
Green Quitar Shuriken per-enhance stats messed up

### ISSUE THREAD

**Issue by nervene** [Ihellmasker/BDO-Planner#15]
Green quitar shuriken drops to 4 AP on PRI, I haven't heard of gear losing stats on enhance so I don't think that is correct.

**Comment by Shadowtrance** [comment]
Argh! another one... i will fix it when i usually fix stuff during maintenance. :)
And no, it isn't correct. :(

**Comment by Shadowtrance** [comment]
And fixed. :)
