### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by SarahD094** [Ihellmasker/BDO-Planner#16]
Great work on this project! I use it all the time and it's so well done. Great UI, especially the compact version.

The only thing I would suggest is when an item has been selected, it appears at the top of the list when you open it back up again. That way you don't have to scroll through to change it from +11 to +12, etc. Another thing is add similar items such as the ultimate version of the gear. Finally, you could have recommended items for the class.

**Comment by Shadowtrance** [comment]
On the first point, it should auto scroll to the item that is equipped for that slot if you open that slot gear list up again.
On the next point, if I'm reading right... all the ultimate and blue variants are already there for gear that has those versions.
And the last point, that's kinda a tough call as everyone has different suggestions/recommendations for each class and varying gear builds.

**Comment by kobitz** [comment]
![image](https://cloud.githubusercontent.com/assets/11189237/23843956/4c209f8c-0763-11e7-8e07-3ad4e4ac4219.png)

**Comment by IJustWantToComment** [comment]
"Resistance to All Status Abnormalities" on the Manos Diamond Necklace can you have it just add 10% to all the "Resistances" instead of it having its own category.
![ex](https://cloud.githubusercontent.com/assets/26762303/24446635/3a335400-143c-11e7-88db-d7210d0b45cc.PNG)

**Comment by Shadowtrance** [comment]
Good catch @IJustWantToComment :) Will fix that.
You should have opened another issue for this but anyway, all good. :)
