### ISSUE TITLE
Missing costumes

### ISSUE THREAD

**Issue by StrykNyne** [Ihellmasker/BDO-Planner#20]
Have you considered adding Jarette's/Delphe Knights/Thermian Casual etc. costumes now that we have the pearl exchange coupon; they can help fill out some of the stats like move speed/crit/attack speed

**Comment by StrykNyne** [comment]
Also, Rhik talisman only has 1 crystal slot

**Comment by Shadowtrance** [comment]
Added and fixed the rhik talisman. :)
