### ISSUE TITLE
Add Striker class

### ISSUE THREAD

**Issue by Shadowtrance** [Ihellmasker/BDO-Planner#21]
Title. :)

Striker just hit KR and will hit NA soon enough, the current class selector kinda bugs out when i add it myself so i guess I'm doing something wrong. haha

Just putting this here so you can get it done at some point, i can get the class pic obviously with my KR account...HQ icon may be an issue though..hmm

And just have it disabled like Dark Knight was before release.
@Ihellmasker

**Comment by Ihellmasker** [comment]
Done ;D
