### ISSUE TITLE
Outfit gender compatibility

### ISSUE THREAD

**Issue by StrykNyne** [Ihellmasker/BDO-Planner#22]
Most of the outfits are gender locked to one or the other, but I'm seeing all of them available on every character. 

Below is a summary of which are available on which gender. 

![image](https://cloud.githubusercontent.com/assets/11142500/25251501/c891929c-25d6-11e7-8322-3b27547ab3a6.png)
![image](https://cloud.githubusercontent.com/assets/11142500/25251514/d42735f8-25d6-11e7-9f1d-d7928761cca3.png)

**Comment by Shadowtrance** [comment]
Yep I'm aware of this, i just added "simple" versions of them as they were asked for which is fair enough to round out stats etc and just left it up to whoever is making the gear set to make sure they have said costume.
Not entirely sure if the current system supports what needs to be done for these though, care to chime in @Ihellmasker ? :)

**Comment by Ihellmasker** [comment]
Nawp, doesn't support it unfortunately. Can't set what classes/genders can use specific gear other than weapons. Probably not really something that's going to be "fixed" either honestly.
