### ISSUE TITLE
Crystal readout showing equipment enhancement level.

### ISSUE THREAD

**Issue by StrykNyne** [Ihellmasker/BDO-Planner#23]
![image](https://cloud.githubusercontent.com/assets/11142500/25399634/37dc5752-29ad-11e7-819b-16a3c671db69.png)

**Comment by Shadowtrance** [comment]
Paging @Ihellmasker :)

**Comment by Ihellmasker** [comment]
Fixeddd, sorry that took a while, I didn't get the notification!
