### ISSUE TITLE
Suggestions Locale EU/NA

### ISSUE THREAD

**Issue by NEOLPAR** [Ihellmasker/BDO-Planner#25]
Great work!

I would suggest to set a filter for EU/NA zones in order to hide the crystals that are not enable on concrete zones.

Kind regards

**Comment by Shadowtrance** [comment]
Good idea, but also not really needed as I've cleaned up all the crystals that we don't have (afaik) and also removed any that i can't find any trace of in NA/EU and KR (don't have access to JP or TW or RU).

If there IS any that I've missed that we DON'T have in NA/EU please do point them out so they can be removed (the exception being the WON, BON and JIN kamasylve crystals as someone requested they be added early :) )
