### ISSUE TITLE
Missing/incorrect item data 

### ISSUE THREAD

**Issue by AryaStark99** [Ihellmasker/BDO-Planner#31]
I believe the data for the following item is incorrect:

Item ID: 15101
Name: Magic Crystal of Infinity - Precision

Under Item Effects it says "Accuracy +2", but in the game it says "All Accuracy +8"

EDIT: This could simply be a matter of terminology (and not a real change), as discussed here:

https://github.com/Ihellmasker/BDO-Planner/issues/27

The Item Effects data for the following item is missing:

Item ID: 11016
Name: Muskan's Shoes

Under Item Effects it says "None", but according to datamined information, the Evasion ranges from 3-43, while the damage reduction ranges from 1-34:

https://docs.google.com/spreadsheets/d/1HE1Lr-7C2ChlCOsBc14z_hY5dkh9tC6tYZFqHgNGIbA/htmlview#

Click on Shoes-tab to see Muskan's Shoes data.

**Comment by Shadowtrance** [comment]
For the first part, i just must have missed that in the accuracy/evasion update. I will fix that to reflect the correct number.

As for muskan's (and other stuff like it with vague descriptions on tooltip like **Increased Evasion & effect increases during Enhancement**)...i always just left it blank in the database as we never had any hard numbers to put to it. The exceptions being items that give bonuses we can actually SEE somewhere like resistances. (like agerian helmet, zereth helmet etc).

Will leave this open for now. :)

**Comment by AryaStark99** [comment]
As for Muskan:

Yeah, I figured it was left out because of lack of any real data (because, like you said, the in-game description doesn't give any specific numbers), but if the datamined information is to be trusted, it offers specific information about evasion stats (specific evasion stats numbers are often shown on items). Of course, it's up to you to decide to leave it out or not, just wanted to let you know :)

By the way, keep up the great work on the planner, I always use it to plan my builds.

**Comment by Shadowtrance** [comment]
All these stats etc are coming soon™
