### ISSUE TITLE
Tadd kunai AP score incorrect

### ISSUE THREAD

**Issue by Lavantant** [Ihellmasker/BDO-Planner#35]
at pri it gives 8 more AP than your site says
(dont know other values, sorry)

**Comment by Shadowtrance** [comment]
Yep another green one that seems to have slipped through the cracks... I'll have to comb over ALL of them just so i can stop having to do this (and have people post issues) at some point. Just a matter of free time.

**Comment by Shadowtrance** [comment]
Pretty sure i squashed all these green weapon issues now. :D
