### ISSUE TITLE
Suggestion - Hidden stats from gear.

### ISSUE THREAD

**Issue by TristisOris** [Ihellmasker/BDO-Planner#36]
Like accuracy from Kzarka, Bheg, Kutum.

There will be sufficient approximate information. Based on guides:
https://docs.google.com/document/d/1f7AC5U1hI82hnonRYx2IumJkvhOKb7gllvYhe1Lbb4Y
https://docs.google.com/document/d/1H4M9vXw3xV0NwLO1xvqDMu-KVRY9CWLY5dccHt0oDOQ

**Comment by Shadowtrance** [comment]
All these stats are coming soon™
