### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by Streusel** [Ihellmasker/BDO-Planner#37]
Basteer - E.g. Talisman, Amulet, etc.
Cash Shop - Knight Cat Armor & Helmet

**Comment by Shadowtrance** [comment]
The first has been addressed previously (the basteer part). Not much point having it to be honest.
And the costumes, well there's NO specific pearl shop costumes, just a general one with the same stats you'd get from one.

**Comment by Streusel** [comment]
How has it been addressed?
And how is there no point in having it? The Basteer Talisman alone provides AP: 5~5 and DP: 5, that's a significant difference from not having the slot filled at all.
