### ISSUE TITLE
Line missing

### ISSUE THREAD

**Issue by Roak** [Ihellmasker/BDO-Planner#38]
All items in planner list 

"Enhancement Effects:
Info Missing.."

Instead of their respective ingame descriptions.

**Comment by Shadowtrance** [comment]
This has already been mentioned here #31 for the most part. Really though that part needs to be changed a little on the backend to work differently to be honest so for now it stays as it is. 

Not really missing much anyway, all the stats that we have actual values for are added. 

Others that don't have a value we KNOW are not, like things that say Accuracy Increase ...we don't know the actual value.

So yeah, for now it stays like that until we either come up with something to work for it or get actual values. :)

**Comment by Shadowtrance** [comment]
All these stats etc are coming soon™
