### ISSUE TITLE
kamasylvia stuff

### ISSUE THREAD

**Issue by Lopasti** [Ihellmasker/BDO-Planner#39]
You added new awakened stones, but most of kamasylvia stuff is missed (like gryphon helmet, new jewelry etc.). Would it be added soon, or planner updates with eu client version (what not the same thing with "soon")?

**Comment by Shadowtrance** [comment]
planner updates are usually done with NA/EU client updates, so when we actually get X place/item etc OR when i have proper translated item names and values to add. 

I do have access to the korean version, but sadly i don't speak or read korean so have to wait for the NA/EU translations to either appear in a patch or in the game files (or on bddatabase) prior to a patch and us getting it.

So for now it's just a waiting game and me compiling a list of things to add. Although if you'd like to help  compiling a list of items please do, it would be a great help. :)

**Comment by Lopasti** [comment]
As you wish. 
Btw: That very important stuff, especially now (after kamasilvia broke all current builds and people trying to optimize all the shit with stones, items and jewelry). Also, thx for your work, bdoplanner is pretty popular thing on RU server.
http://i.imgur.com/xIA40mn.png

1. Griffon's Helmet

description: Helmet owns a powerful aura of griffon's King. 

effect: 

All ressistance +5%
Damage absorption +3

Enchant: Same as Giath's.

2. Andeliff's earring

AP 8-8

description: This earrings These earrings are given only to those who have proved their commitment to Kamasilvia. They are imbued with a special aura of the Lemoria forest.

Enchant: no enchant (quest item)

3. Karnak's earring

AP 5-5

description: Earrings are made of two powerful artifacts, these can be found only in the vastness of the great Kamasilvia. You can strengthen the corresponding earrings, but in case of failure both will disappear.

effect: 

Additional damage to kamasilvia monsters +3

Enchant: +2 AP +1 DP Additional damage to kamasilvia monsters +1

4. Belt of the Veltar's shine

AP 5-5

description: The belt absorbed the light of hundreds of sinless souls. You can strengthen the corresponding belt, but in case of failure both will disappear.

effect: +80 LT

Enchant: 3 AP 25 HP

**Comment by Shadowtrance** [comment]
Ok this is everything I've been able to dig up for kama items. Don't think i missed anything.
Some I've just google translated so the names might be stupid. haha
Really hope we get kama soon so this stuff can be added with proper names, well NA/EU translation anyway.

| Item Name |   | Link |
| :-------------: |:--:| :-----:|
| Griffon's Helmet |  | http://bddatabase.net/us/item/11101/ |
| Lemoria Helmet   |  | http://bddatabase.net/us/item/11070/ |
| Lemoria Armor    |  | http://bddatabase.net/us/item/11071/ |
| Lemoria Gloves |  | http://bddatabase.net/us/item/11072/ |
| Lemoria Shoes |  | http://bddatabase.net/us/item/11073/ |
| Unknown Gloves (new boss gloves) |  | http://bddatabase.net/us/item/11102/ |
| Urgon's Shoes (new boss shoes) |  | http://bddatabase.net/us/item/11103/ |
| Ring of Forest Lona Ross (unsure of translation) |  | http://bddatabase.net/us/item/12042/ |
| Harmony of Grana Ring |  | http://bddatabase.net/us/item/12043/ |
| Valtarra's Hidden Light Belt |  | http://bddatabase.net/us/item/12236/ |
| Tungrad Belt |  | http://bddatabase.net/us/item/12237/ |
| Protection of Grana Necklace |  | http://bddatabase.net/us/item/11639/ |
| Anbelif's (Andelif's ?) Earring |  | http://bddatabase.net/us/item/11831/ |
| Narc (Karnak's ?) Earring |  | http://bddatabase.net/us/item/11834/ |
| Oath of Grana Earring |  | http://bddatabase.net/us/item/11837/ |

**Comment by Shadowtrance** [comment]
kama 2 has come, nearly everything is added besides those boss gloves (think they're not released anywhere yet).
