### ISSUE TITLE
Wrong AP (Kutum Sub-weapon)

### ISSUE THREAD

**Issue by StrykNyne** [Ihellmasker/BDO-Planner#4]
At TET, it is listed as 25-28, but it is actually 25-27. Also (as far as I can tell) the calculator doesn't take into account decimal values for AP. 

Example: In game, a TRI Dandelion will be 2 points higher AP than a Kzarka at the same level, but if you equip a Rosar offhand which gives 12-15 AP, the sheet AP will shift so that the dandelion is 3 points higher.

**Comment by Ihellmasker** [comment]
Hmm, not sure what happened with the Kutum weapons having extra AP, I'll have to fix that or maybe @Shadowtrance can *winkwinknudgenudge*

As for the decimal values, it should count them. It's not actually doing what you said for me weirdly enough.

![kzarka](https://cloud.githubusercontent.com/assets/3030516/22447700/eff4b5b8-e74b-11e6-9237-516a581d31b0.png)

It's possible it's caching an old version for you maybe because I did fix that issue recently. Can you try clearing your browsers cache and testing again, and if you do get the problem again, can you give me a link for a gear set in which it has that issue?

Thanks!

**Comment by StrykNyne** [comment]
It will round down if the value after all is added together ends in a decimal. 

My in game AP is 194/204 with TRI: Nouver Shield, and 170/181 with TRI: Rosar Shield

Also, the equipment tooltip in game will show decimal values when changing between Rosar, and Nouver.
It shows a difference of 25.5AP

**Comment by StrykNyne** [comment]
I can provide screenshots if necessary, but it may have to wait until I get back to my home computer. BDO runs like a cripple on my laptop.

**Comment by Ihellmasker** [comment]
Yeah, if you can please show screenshots... I was specifically told that wasn't the case previously [here](https://www.reddit.com/r/blackdesertonline/comments/5owdae/tool_bdo_planner_gear_calculator_update/dcnfvww/) so changes were made to stop it doing that.

**Comment by StrykNyne** [comment]
![maxthonsnap20170130174735](https://cloud.githubusercontent.com/assets/11142500/22448138/70537e16-e714-11e6-8998-ae3acaa00540.png)
![maxthonsnap20170130174826](https://cloud.githubusercontent.com/assets/11142500/22448140/70571efe-e714-11e6-840a-df3303daa462.png)
![maxthonsnap20170130174904](https://cloud.githubusercontent.com/assets/11142500/22448139/70569f42-e714-11e6-88d0-fe2a7b659570.png)

**Comment by StrykNyne** [comment]
Also, upon further inspection of the source of the change, it's because of the Kutum offhand issue that initially sparked this ticket. Kutum gives an even AP, not a decimal.

**Comment by StrykNyne** [comment]
As a further thought; because of the decimal AP not showing up, leading people to believe that it's being calculated incorrectly, what about including the decimal AP values in the breakdown, but not the sheet AP?

**Comment by Ihellmasker** [comment]
Ahh... I see what you mean... Yeah I guess that's what's happened. Well that's a bit annoying to say the least.

Oh well. I'll get it fixed over the next few days, gotta unwrite the code...

@Shadowtrance Can you fix the Kutum AP values please while I fix the other stuff.

**Comment by StrykNyne** [comment]
Also, one more tidbit before the ticket gets closed. 
![image](https://cloud.githubusercontent.com/assets/11142500/22448743/b31b3956-e718-11e6-9336-afb1b3f553f3.png)

**Comment by Shadowtrance** [comment]
Yep will fix kutum and the wiz resist and whatever else i find tomorrow during maintenance. :)

**Comment by StrykNyne** [comment]
Merci!

**Comment by Ihellmasker** [comment]
Mkay, well, I've fixed all of that stuff fortunately without too much of a problem. We should release it in the next few days, we just identified a few other items that have wrong stats so we're gonna fix those and do an update with it all in.

**Comment by Ihellmasker** [comment]
Okay, the updates posted up now so give it a try and let us know if it's all working for you, if you don't mind.
