### ISSUE TITLE
Incorrect item data

### ISSUE THREAD

**Issue by lostvayne** [Ihellmasker/BDO-Planner#41]
The data for this item is incorrect:
Item ID: 12233
Name: Helm Destroyer’s Belt

When scaling from PRI to DUO, TRI, TET, and PEN, the DP is incorrect. I believe 1 DP is added every upgrade because my DUO is 5 AP and 2 DP as seen [here](https://gyazo.com/af8238fb06f9cb2eb3f95b718c6dfa74) which differs from the 5 AP and 5 DP that it says on BDO Planner. I believe it should be 5 AP & 2 DP for DUO, 6 AP & 3 DP for TRI, 7 AP and 4 DP for TET, and 8 AP & 5 DP for PEN.

**Comment by Shadowtrance** [comment]
Thanks for pointing this out. And fixed. :)
