### ISSUE TITLE
Incorrect Item Enhancements

### ISSUE THREAD

**Issue by TheGreenkey** [Ihellmasker/BDO-Planner#44]
These items all seem to be two DP lower than the actual in-game/bdodatabase items when enhancing:

Taritas Helmet (ID: 10813)
Taritas Helmet of Iron Wall (ID: 10841)
Taritas Helmet of Agility (ID: 10845)
Taritas Helmet of Intimidation (ID: 10849)

Zereth Helmet (ID: 10817)
Zereth Helmet of Iron Wall (ID: 10857)
Zereth Helmet of Agility (ID: 10861)
Zereth Helmet of Intimidation (ID: 10865)

Also checked all other available helmets and they all seemed to have correct enhancement data.

**Comment by Shadowtrance** [comment]
thanks for the report :) and fixed. :)
