### ISSUE TITLE
Awakened AP Tooltip

### ISSUE THREAD

**Issue by shaeeee** [Ihellmasker/BDO-Planner#45]
In the Awakened AP tooltip, "Total AP" shows NaN if "statless" accessories are used, i.e. rings with no AP nor DP, (Kalis Ring for accuracy, Yuria Ring for Human Damage etc.).

**Comment by Shadowtrance** [comment]
Good catch! never noticed that.

paging dr @Ihellmasker !

**Comment by Shadowtrance** [comment]
This should be fixed now thanks to @Roma149 :)
