### ISSUE TITLE
Enhancement Increaser/Decreaser

### ISSUE THREAD

**Issue by DrWittMDPhD** [Ihellmasker/BDO-Planner#47]
One feature I think would be useful is the ability to increase or decrease the enchant level of an item without having to open up the menu again. It's time consuming and quite annoying to wait for the list to auto scroll you to what is currently equipped and to have to count each tick to click the specific enhance level that you want. I was thinking that a small plus or minus sign on each piece of gear that would increment the level by 1 would be very useful to quickly change the levels on an item so you can play around with gear to see what you need to reach a certain goal. It may be a small feature, but I think it will be a welcome QoL change!
I was thinking something like this: https://cdn.discordapp.com/attachments/288205092224630785/385293288330231819/Gear_With_Enhance_Incrementers.png
Obviously the buttons would be changed to fit the theme, but this gets my thoughts across.

**Comment by Shadowtrance** [comment]
Could you possibly share another image of your mockup/idea? that link doesn't work sadly. :(

**Comment by DrWittMDPhD** [comment]
Sorry, hopefully this works.
http://puu.sh/yGpPN/6f0e5212ea.png

**Comment by mike-seven** [comment]
As an addition it would be nice if user can setup 'default' enchantment level for all lists of items showing after clicking a slot. It could be 3 separate defaults, one for armor pieces, one for accesories and one for weapons. When you setup armor default enchantment for TRI and click on slot, all armors will appear with TRI enchantment selected. The same for the other item types.

**Comment by Ihellmasker** [comment]
v2 will be redesigned and simplified in places which should make adjusting enhancement levels much easier and less cumbersome. Adding small buttons like that may be a bit awkward with the new interface but changing items and enhancement levels will be easier anyway (Not having a giant popup appear and scroll and no slider for level selection.
