### ISSUE TITLE
Missing required configuration template

### ISSUE THREAD

**Issue by Zumochi** [Ihellmasker/BDO-Planner#48]
Hey!

Trying to setup this application myself, I can see two missing files which understandably have sensitive information, but not having templates of them makes it really hard to get the right values, unless you reverse engineer a bit.

* `/assets/js/bdo_database.js`
* `/php/ga.php`

Can we get some templates or the files with the values blanked out? I can put them in the repo and make a PR if you like.

Thanks!

**Comment by Ihellmasker** [comment]
Hey there

- bdo_database.js is just https://github.com/Ihellmasker/BDO-Planner/blob/master/src/php/bdo_database.php but I use a .htaccess to rename it to a .js file.
- ga.php is just a google analytics script block, you can safely delete that without it effecting anything.
