### ISSUE TITLE
I Pri: Manos Diamond Necklace

### ISSUE THREAD

**Issue by amiricas** [Ihellmasker/BDO-Planner#5]
Hi, you have incorrect information on upgraded versions of Manos Diamond Necklace, For example Pri version have +11AP and 11% of all resistance. Thx for fixing

**Comment by Shadowtrance** [comment]
Umm i don't know what PRI Manos DIamond Necklace stats you're looking at but i just checked our database and ingame and they match. PRI = 9 AP 11% resist.

**Comment by Ihellmasker** [comment]
Assuming [this](http://bddatabase.net/us/item/11730/#1) is the item you're referring too, ours is correct based on that.

If you think it's wrong, please show a screenshot of your item ingame.
