### ISSUE TITLE
Costume Gear Specials (bonus effects)

### ISSUE THREAD

**Issue by Shauneh13** [Ihellmasker/BDO-Planner#50]
This is a tiny correction nothing big. If i'm not mistaken, the bonus effect on costumes should read 

Awakening Weapon's Durability Consumption: -10%
Main Weapon's Durability Consumption: -10%

It currently is missing the minus sign, indicating it consumes more lol.

Awakening Weapon's Durability Consumption: 10%
Main Weapon's Durability Consumption: 10%

Most people won't see this as an issue because they know better, but new people might be confused. Just a heads up, thanks for the great site, and you and your teams efforts.

**Comment by Shadowtrance** [comment]
Ah yep cool. good catch :)
I will fix that. :)

**Comment by Shadowtrance** [comment]
And fixed.
