### ISSUE TITLE
Erronious Krea Knot Stats?

### ISSUE THREAD

**Issue by Carniveron** [Ihellmasker/BDO-Planner#53]
Since the most recent update, Tri Ultimate Krea Knot stats are random nonsense numbers. 

Actual in game:

14 ~ 27 AP
8 DP

This showed accurately in the tool for a long time

New stats in the tool today:

12 ~ 14 AP
30 DP

Really strange numbers

**Comment by Shadowtrance** [comment]
argh yep you're right :(
i guess i screwed up in the haze of numbers from all the hidden stats and copy/pasted wrong. :(
I will fix it as soon as i can. :)

**Comment by Shadowtrance** [comment]
**Should** be all fixed (hopefully). Might have to force refresh/reload the page for changes to appear with CTRL F5.

**Comment by Carniveron** [comment]
Nice work on the quick fix
