### ISSUE TITLE
not working  help pls.

### ISSUE THREAD

**Issue by berkay1074** [Ihellmasker/BDO-Planner#54]
hi try added website but not working 

http://deneme.trblackdesert.com/

where is wrong?

**Comment by Shadowtrance** [comment]
I suggest you read the [readme](https://github.com/Ihellmasker/BDO-Planner/blob/master/README.md) closely, it has the solution to your problem.

**Comment by berkay1074** [comment]
htaccess 
RewriteEngine on

<IfModule mod_rewrite.>
RewriteEngine On
RewriteBase /
RewriteRule ^assets/js/bdo_database.js$ php/bdo_database.php [NC,L]
</IfModule>

is it correct
?
