### ISSUE TITLE
htaccess options

### ISSUE THREAD

**Issue by berkay1074** [Ihellmasker/BDO-Planner#57]
htaccess  Can you share settings?

http://deneme.trblackdesert.com/
is working , but not save and creating  page opening 

http://deneme.trblackdesert.com/save/[[4],[-1,0,[-1,-1]],[-1,0,[-1,-1]],[-1,0,[-1,-1]],[-1,0,[-1,-1]],[[12001,0],[12001,0]],[[-1,0],[-1,0]],[-1,0],[-1,0],[-1,0,[-1,-1]],[-1,0],[-1,0,[-1,-1]],[-1],[-1,[-1]],[-1],[-1],[-1],[-1]]

loom 404 not found

**Comment by Ihellmasker** [comment]
The htaccess settings are shown on the front page.

If you need to know more on htaccess, I suggest googling it.

**Comment by berkay1074** [comment]
how to fix the save page ?
