### ISSUE TITLE
Missing hidden evasion on Bensho Necklace

### ISSUE THREAD

**Issue by SuraKatana** [Ihellmasker/BDO-Planner#61]
Bensho necklace has double the hidden evasion as sheet evasion. I didn't realize it was missing until someone referenced that sicil had more evasion because they didn't know. Here's the sheet.  https://docs.google.com/spreadsheets/d/1At9HBPDYrdOgXJpDYDy6EmvBPo_S2Be1pqwuckPNFqQ/edit#gid=0

**Comment by Shadowtrance** [comment]
Fixed. :)
