### ISSUE TITLE
Issue with how Accuracy is displayed

### ISSUE THREAD

**Issue by Aoize** [Ihellmasker/BDO-Planner#62]
Im reporting an issue i recently found with BDO Planner in how Accuracy is counted. Im working with a sorc gear currently, it seems that bheg gloves and kzarka count added accuracy then shown in game. I have attached a link to the images showing this.

To sum up the images. A tet kzarka with a +8 accuracy crystal in game displays 383 Accuracy, on BDO planner, a tet kzarka with no +8 crystal displays 383 Accuracy. Its a small issue but thought you would be interesting in knowing about it.

https://imgur.com/a/TZRqX

**Comment by Shadowtrance** [comment]
Crystals aren't shown in the total ingame in the AP / DP tooltips, not accuracy, not evasion, nothing. Only what comes straight from the items themselves.
