### ISSUE TITLE
[bug] Valencia rings , set effect not counting

### ISSUE THREAD

**Issue by ShadoweCZ** [Ihellmasker/BDO-Planner#65]
set effect of Valencia Quest reward rings is not counted
Sahazad's Ring of Monarch
Barhan's Ring of Conquest
etc ..

**Comment by Shadowtrance** [comment]
Not seeing any issue on my end at all.

The ring set effects apply to either:

Sahazad's Ring of Monarch x2
or
Barhan's Ring of Conquest x2

**OR**

Sahazad's Ring of Monarch x1
and
Barhan's Ring of Conquest x1

which is **Extra AP Against Monsters +7** in the "Extra Damage" stat section

**AND**

Manmehan's Ring of Gold x2
or
Saya's Ring of Eternity x2

**OR**

Manmehan's Ring of Gold x1
and
Saya's Ring of Eternity x1

which is **Damage from Monsters Slightly Reduced +5%** in  the "Gear Specials" stat section
