### ISSUE TITLE
Shroud Knights Armor

### ISSUE THREAD

**Issue by KnightDoom** [Ihellmasker/BDO-Planner#70]
Shroud Knight armor is listed as movement +2 incorrectly.

Shroud Knight Armor is CS +1,  AS +1 , Amity +15%
http://bddatabase.net/us/item/12597/

**Comment by Shadowtrance** [comment]
Yep you're right, I'll fix that. :)

**Comment by Shadowtrance** [comment]
And should be fixed now :)
