### ISSUE TITLE
Wrong effects on Costumes

### ISSUE THREAD

**Issue by Kamiikaze** [Ihellmasker/BDO-Planner#75]
In this Build: https://bdoplanner.com/s/zvvlpoMn
is a **Shroud Knights Armor** who say _"Movement +2 & Amity"_
But ingame and in BDOdatabase it have _atk.speed / cast speed +1_
See here: http://bddatabase.net/us/item/12590/

The movement speed effect is available from this:
http://bddatabase.net/us/item/14203/
http://bddatabase.net/us/item/14303/

**Comment by Shadowtrance** [comment]
Should be fixed now.
