### ISSUE TITLE
Missing DP on Necklace of Sealed Magical Power

### ISSUE THREAD

**Issue by Jaby-JB** [Ihellmasker/BDO-Planner#77]
The DP stat is missing on the "Necklace of Sealed Magical Power".
Hidden DP stats are still displayed correctly but the missing sheet DP messes with the Gearscore.
![image](https://user-images.githubusercontent.com/29146860/37585278-e0ce15aa-2b58-11e8-8533-8f28a4aa68e1.png)

**Comment by Shadowtrance** [comment]
Should be fixed now.
