### ISSUE TITLE
Cron Stone Energy levels

### ISSUE THREAD

**Issue by TashWildthing** [Ihellmasker/BDO-Planner#78]
Thank you for your work!

Could you please add the Cron Stone Energy levels?

Thank you!

**Comment by Shadowtrance** [comment]
Seeing as... 
1. NA/EU doesn't have it, and no idea if/when it will come. and 
2. I don't have any info on it whatsoever to be able to add anything even if i wanted to. and 
3. It would break our rule of not adding things before official NA/EU release which is the region we follow with regards to bdoplanner.

So short answer is, no (not yet).
