### ISSUE TITLE
Ring of Cadry Guardian does not add AP to total

### ISSUE THREAD

**Issue by drp1098** [Ihellmasker/BDO-Planner#79]
https://bdoplanner.com/save/[[14],[10961,18,[15224,15628]],[10962,18,[15852,15206]],[10964,18,[15631,15631]],[10963,18,[15630,15630]],[[12044,0],[12032,0]],[[11838,0],[11838,0]],[12220,2],[11613,2],[11209,18,[15639,15632]],[14833,18],[11311,18,[15627,-1]],[-1],[-1,[-1]],[-1],[-1],[-1],[-1]]

**Comment by Shadowtrance** [comment]
Cadry is a **DP** ring.

# **DP**

**Comment by drp1098** [comment]
You're right! TY
