### ISSUE TITLE
Bosses

### ISSUE THREAD

**Issue by hemisfere** [Ihellmasker/BDO-Planner#8]
- add boss items (boss set)
- add all items

**Comment by Ihellmasker** [comment]
All items are added? What is missing?

**Comment by Shadowtrance** [comment]
This is not helpful at all...
Maybe post a short sentence of what the actual issue is, we aren't mind readers.
This is basically like someone commenting and saying "hey, it doesn't work!"... **WHAT** doesn't work, or in this case, **WHAT** is the issue.
Yes, I'm going to keep repeating myself...
